services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/strongpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

  social-network-backend:
    build:
      context: ./social-network-backend
    container_name: social-network-backend
    ports:
      - "3000:3000"
    volumes:
      - ./social-network-backend:/app
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=strongpassword
    depends_on:
      - neo4j
    networks:
      - app-network
    command: ["yarn", "start"]

  social-network-frontend:
    build:
      context: ./social-network-frontend
    container_name: social-network-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./social-network-frontend:/app
    depends_on:
      - social-network-backend
    networks:
      - app-network
    command: ["yarn", "start"]

networks:
  app-network:
    driver: bridge

volumes:
  neo4j-data:
